import {
  Booking,
  Guest,
  HousekeepingTask,
  ResortNotification,
  RestaurantOrder,
  Room,
} from "./types";

export const initialBookings: Booking[] = [
  {
    id: "BK-8091",
    guestName: "Priya Sharma",
    guestEmail: "priya.sharma@luxmail.com",
    guestPhone: "+91 98201 44521",
    roomName: "Deluxe Sea View Suite",
    roomCode: "R-204",
    checkIn: "2026-09-25",
    checkOut: "2026-09-29",
    nights: 4,
    totalAmount: "₹96,000",
    status: "Checked In",
    loyaltyTier: "Platinum",
    guestsCount: 2,
    specialRequests: "Honeymoon setup, chilled champagne, extra Egyptian cotton towels",
  },
  {
    id: "BK-8092",
    guestName: "Rahul Mehta",
    guestEmail: "rahul.mehta@investcorp.in",
    guestPhone: "+91 98112 39014",
    roomName: "Private Garden Villa",
    roomCode: "G-12",
    checkIn: "2026-09-25",
    checkOut: "2026-09-28",
    nights: 3,
    totalAmount: "₹84,000",
    status: "Confirmed",
    loyaltyTier: "Gold",
    guestsCount: 3,
    specialRequests: "Private yoga instructor at dawn, vegan breakfast platter",
  },
  {
    id: "BK-8093",
    guestName: "Lady Ananya Iyer",
    guestEmail: "ananya.iyer@heritage.org",
    guestPhone: "+91 98450 11982",
    roomName: "Premier Ocean Pool Villa",
    roomCode: "V-07",
    checkIn: "2026-09-26",
    checkOut: "2026-10-02",
    nights: 6,
    totalAmount: "₹2,10,000",
    status: "Pending",
    loyaltyTier: "VIP",
    guestsCount: 2,
    specialRequests: "Helicopter helipad arrival transfer, Sunset yacht reservation on Day 2",
  },
  {
    id: "BK-8094",
    guestName: "Sir Julian Vance",
    guestEmail: "j.vance@mayfairholdings.co.uk",
    guestPhone: "+44 7700 900142",
    roomName: "Presidential Royal Suite",
    roomCode: "S-301",
    checkIn: "2026-09-24",
    checkOut: "2026-09-30",
    nights: 6,
    totalAmount: "₹3,40,000",
    status: "Checked In",
    loyaltyTier: "Platinum",
    guestsCount: 4,
    specialRequests: "Private cellar tasting with Sommelier, 24/7 dedicated butler",
  },
  {
    id: "BK-8095",
    guestName: "Dr. Elena Rostova",
    guestEmail: "elena.rostova@genevabiotech.ch",
    guestPhone: "+41 22 555 0184",
    roomName: "Cliffside Sanctuary Villa",
    roomCode: "C-102",
    checkIn: "2026-09-27",
    checkOut: "2026-10-01",
    nights: 4,
    totalAmount: "₹1,60,000",
    status: "Confirmed",
    loyaltyTier: "Gold",
    guestsCount: 1,
    specialRequests: "Quiet zone guarantee, Ayurvedic herbal bath preparation",
  },
  {
    id: "BK-8096",
    guestName: "Vikramaditya Singhania",
    guestEmail: "vikram@singhaniagroup.com",
    guestPhone: "+91 98210 77332",
    roomName: "Ocean Pool Villa",
    roomCode: "V-04",
    checkIn: "2026-09-22",
    checkOut: "2026-09-26",
    nights: 4,
    totalAmount: "₹1,40,000",
    status: "Checked Out",
    loyaltyTier: "Platinum",
    guestsCount: 2,
    specialRequests: "Late checkout at 3:00 PM accommodated",
  },
];

export const initialRooms: Room[] = [
  {
    id: "RM-1",
    code: "V-07",
    name: "Premier Ocean Pool Villa",
    type: "Villa",
    view: "Direct Ocean Front",
    wing: "North Coral Bay",
    ratePerNight: "₹35,000",
    status: "Ready",
    capacity: 3,
    sqm: 165,
    features: ["Private Infinity Pool", "Butler Pantry", "Outdoor Rain Shower", "Wine Reserve"],
    currentGuest: undefined,
    assignedStaff: "Deepak Sharma",
  },
  {
    id: "RM-2",
    code: "S-301",
    name: "Presidential Royal Suite",
    type: "Penthouse Suite",
    view: "360° Panoramic Coastline",
    wing: "The Grand Pavilion",
    ratePerNight: "₹65,000",
    status: "Occupied",
    capacity: 4,
    sqm: 240,
    features: ["Grand Piano", "Private Jacuzzi Terrace", "Dedicated Butler", "Private Dining Room"],
    currentGuest: "Sir Julian Vance",
    assignedStaff: "Maria Fernandes",
  },
  {
    id: "RM-3",
    code: "G-12",
    name: "Private Garden Villa",
    type: "Villa",
    view: "Tropical Botanical Gardens",
    wing: "Orchid Sanctuary",
    ratePerNight: "₹28,000",
    status: "Occupied",
    capacity: 3,
    sqm: 120,
    features: ["Sunken Garden Bath", "Private Hammock Grove", "Espresso Bar", "Bespoke Scents"],
    currentGuest: "Rahul Mehta",
    assignedStaff: "Karan Joshi",
  },
  {
    id: "RM-4",
    code: "R-204",
    name: "Deluxe Sea View Suite",
    type: "Suite",
    view: "Sunset Arabian Sea",
    wing: "Azure Terraces",
    ratePerNight: "₹24,000",
    status: "Occupied",
    capacity: 2,
    sqm: 95,
    features: ["Teak Balcony Daybed", "Marble En-suite", "Bose Sound System", "Pillow Menu"],
    currentGuest: "Priya Sharma",
    assignedStaff: "Sunita Rao",
  },
  {
    id: "RM-5",
    code: "C-102",
    name: "Cliffside Sanctuary Villa",
    type: "Villa",
    view: "Elevated Cliff Edge",
    wing: "Falcon Crest",
    ratePerNight: "₹40,000",
    status: "Ready",
    capacity: 2,
    sqm: 145,
    features: ["Glass-Bottom Plunge Pool", "Fire Pit Terrace", "Telescope Deck", "Organic Bar"],
    currentGuest: undefined,
    assignedStaff: "Amitava Sen",
  },
  {
    id: "RM-6",
    code: "R-205",
    name: "Deluxe Sea View Suite",
    type: "Suite",
    view: "Sunset Arabian Sea",
    wing: "Azure Terraces",
    ratePerNight: "₹24,000",
    status: "Housekeeping",
    capacity: 2,
    sqm: 95,
    features: ["Teak Balcony Daybed", "Marble En-suite", "Bose Sound System", "Pillow Menu"],
    currentGuest: undefined,
    assignedStaff: "Sunita Rao",
  },
  {
    id: "RM-7",
    code: "V-02",
    name: "Beachfront Lagoon Villa",
    type: "Villa",
    view: "Private Sand Beach",
    wing: "South Cove",
    ratePerNight: "₹38,000",
    status: "Maintenance",
    capacity: 4,
    sqm: 175,
    features: ["Private Boardwalk to Beach", "Plunge Pool", "Outdoor Teppanyaki", "Kayak Bay"],
    currentGuest: undefined,
    assignedStaff: "Ramesh Pillai",
  },
  {
    id: "RM-8",
    code: "G-14",
    name: "Royal Botanical Villa",
    type: "Villa",
    view: "Private Lotus Pond",
    wing: "Orchid Sanctuary",
    ratePerNight: "₹32,000",
    status: "Ready",
    capacity: 3,
    sqm: 130,
    features: ["Lotus Pavilion", "Outdoor Stone Tub", "Aromatherapy Shower", "Butler Service"],
    currentGuest: undefined,
    assignedStaff: "Karan Joshi",
  },
];

export const initialGuests: Guest[] = [
  {
    id: "GST-1",
    name: "Sir Julian Vance",
    email: "j.vance@mayfairholdings.co.uk",
    country: "United Kingdom",
    avatar: "JV",
    loyaltyTier: "Platinum",
    totalStays: 7,
    totalSpent: "₹14,80,000",
    currentRoom: "S-301 · Presidential Suite",
    preferences: "Prefers Chateau Margaux 2015, Morning English Breakfast in bed at 08:00, Daily The Times printout",
    status: "In Residence",
  },
  {
    id: "GST-2",
    name: "Priya Sharma",
    email: "priya.sharma@luxmail.com",
    country: "India",
    avatar: "PS",
    loyaltyTier: "Platinum",
    totalStays: 4,
    totalSpent: "₹4,20,000",
    currentRoom: "R-204 · Deluxe Sea View",
    preferences: "Allergen: Shellfish. Enjoys sunset yoga and cold-pressed Valencia orange juice",
    status: "In Residence",
  },
  {
    id: "GST-3",
    name: "Lady Ananya Iyer",
    email: "ananya.iyer@heritage.org",
    country: "India",
    avatar: "AI",
    loyaltyTier: "Platinum",
    totalStays: 9,
    totalSpent: "₹19,50,000",
    currentRoom: "V-07 · Pool Villa (Assigned)",
    preferences: "Always reserves private yacht for full sunset cruise; prefers silk pillowcases and organic spa oils",
    status: "Arriving Today",
  },
  {
    id: "GST-4",
    name: "Rahul Mehta",
    email: "rahul.mehta@investcorp.in",
    country: "India",
    avatar: "RM",
    loyaltyTier: "Gold",
    totalStays: 3,
    totalSpent: "₹3,10,000",
    currentRoom: "G-12 · Garden Villa",
    preferences: "High-speed Ethernet required for international teleconferences; strictly vegetarian",
    status: "In Residence",
  },
  {
    id: "GST-5",
    name: "Dr. Elena Rostova",
    email: "elena.rostova@genevabiotech.ch",
    country: "Switzerland",
    avatar: "ER",
    loyaltyTier: "Gold",
    totalStays: 2,
    totalSpent: "₹2,80,000",
    currentRoom: "C-102 · Cliffside Villa",
    preferences: "Deep-tissue massage at Ocean Spa daily at 17:00; Sparkling San Pellegrino in suite",
    status: "Upcoming",
  },
];

export const initialOrders: RestaurantOrder[] = [
  {
    id: "KOT-301",
    table: "Table 4 · Sunset Terrace",
    venue: "Sunset Terrace (Fine Dining)",
    guestName: "Sir Julian Vance",
    items: [
      "Grilled Chilean Sea Bass with Saffron Foam",
      "Black Truffle & Wild Morel Risotto",
      "Meursault Premier Cru 2020 (Bottle)",
    ],
    totalAmount: "₹14,500",
    time: "19:15",
    stage: "Preparing",
  },
  {
    id: "KOT-302",
    table: "Table 9 · The Ocean Club",
    venue: "The Ocean Club (Seafood & Grill)",
    guestName: "Priya Sharma",
    items: [
      "Pan-seared Coral Bay Scallops (substituted for King Oyster Mushroom)",
      "Avocado & Palm Heart Carpaccio",
      "Dom Pérignon Vintage 2013",
    ],
    totalAmount: "₹22,000",
    time: "19:28",
    stage: "Plated",
  },
  {
    id: "KOT-303",
    table: "Cabana 2 · Azure Pool Lounge",
    venue: "Azure Lounge (Cocktails & Tapas)",
    guestName: "Rahul Mehta",
    items: [
      "Wood-fired Artisanal Fig & Goat Cheese Flatbread",
      "Heirloom Tomato Gazpacho",
      "Virgin Yuzu Sparkler x2",
    ],
    totalAmount: "₹4,200",
    time: "19:40",
    stage: "Received",
  },
  {
    id: "KOT-300",
    table: "Private Dining Cellar",
    venue: "The Sommelier Cellar",
    guestName: "Vikramaditya Singhania",
    items: [
      "7-Course Degustation with Grand Cru Pairing",
      "A5 Miyazaki Wagyu Tenderloin",
      "Valrhona Dark Chocolate Soufflé",
    ],
    totalAmount: "₹48,000",
    time: "18:30",
    stage: "Served",
  },
];

export const initialHousekeeping: HousekeepingTask[] = [
  {
    id: "HK-101",
    roomCode: "V-07",
    roomName: "Premier Ocean Pool Villa",
    priority: "VIP Arrival",
    taskType: "VIP Arrival Inspection & Orchid Welcome Arrangement",
    assignedTo: "Deepak Sharma",
    dueTime: "12:00 PM",
    status: "Completed",
  },
  {
    id: "HK-102",
    roomCode: "S-301",
    roomName: "Presidential Royal Suite",
    priority: "High",
    taskType: "Daily Midday Refresh & Fresh Linen Change",
    assignedTo: "Maria Fernandes",
    dueTime: "01:30 PM",
    status: "Inspected",
  },
  {
    id: "HK-103",
    roomCode: "R-205",
    roomName: "Deluxe Sea View Suite",
    priority: "Standard",
    taskType: "Post-checkout Deep Sanitize & Teak Balcony Polish",
    assignedTo: "Sunita Rao",
    dueTime: "02:30 PM",
    status: "In Progress",
  },
  {
    id: "HK-104",
    roomCode: "G-12",
    roomName: "Private Garden Villa",
    priority: "Turn-down",
    taskType: "Evening Turn-down Service, Lavender Mist & Pillow Menu",
    assignedTo: "Karan Joshi",
    dueTime: "07:00 PM",
    status: "Pending",
  },
];

export const initialNotifications: ResortNotification[] = [
  {
    id: "NOTIF-1",
    title: "VIP Arrival: Lady Ananya Iyer",
    detail: "Helicopter arrival scheduled at 14:15. Helipad buggy and champagne welcome ready at Pavilion A.",
    time: "10 mins ago",
    department: "Concierge",
    unread: true,
    priority: "urgent",
  },
  {
    id: "NOTIF-2",
    title: "Suite S-301 Inspection Approved",
    detail: "Presidential Suite 301 passed 5-star QA inspection checklist with 100% rating.",
    time: "25 mins ago",
    department: "Housekeeping",
    unread: true,
  },
  {
    id: "NOTIF-3",
    title: "Sunset Terrace Dinner Fully Booked",
    detail: "Sunset Terrace fine dining has reached 100% reservation capacity for 20:00 seating.",
    time: "1 hour ago",
    department: "Kitchen",
    unread: false,
  },
  {
    id: "NOTIF-4",
    title: "High Tide Advisory",
    detail: "High tide expected at 17:45 (+2.1m). Coastal security has secured the south beach loungers.",
    time: "2 hours ago",
    department: "General",
    unread: false,
  },
];
