import {
  Account,
  Booking,
  Guest,
  GuestReview,
  HousekeepingTask,
  LostAndFoundItem,
  PromotionCode,
  ReservationFolio,
  ResortNotification,
  ResortPolicy,
  ResortServiceItem,
  RestaurantOrder,
  RolePermission,
  Room,
  ServiceBooking,
  SupportTicket,
} from "./types";

export const initialBookings: Booking[] = [
  {
    id: "BK-8091",
    guestName: "Priya Sharma",
    guestEmail: "priya.sharma@luxmail.com",
    guestPhone: "+91 98201 44521",
    roomName: "Deluxe Sea View Suite",
    roomCode: "R-204",
    checkIn: "2026-09-25",
    checkOut: "2026-09-29",
    nights: 4,
    totalAmount: "₹96,000",
    status: "Checked In",
    loyaltyTier: "Platinum",
    guestsCount: 2,
    specialRequests: "Honeymoon setup, chilled champagne, extra Egyptian cotton towels",
  },
  {
    id: "BK-8092",
    guestName: "Rahul Mehta",
    guestEmail: "rahul.mehta@investcorp.in",
    guestPhone: "+91 98112 39014",
    roomName: "Private Garden Villa",
    roomCode: "G-12",
    checkIn: "2026-09-25",
    checkOut: "2026-09-28",
    nights: 3,
    totalAmount: "₹84,000",
    status: "Confirmed",
    loyaltyTier: "Gold",
    guestsCount: 3,
    specialRequests: "Private yoga instructor at dawn, vegan breakfast platter",
  },
  {
    id: "BK-8093",
    guestName: "Lady Ananya Iyer",
    guestEmail: "ananya.iyer@heritage.org",
    guestPhone: "+91 98450 11982",
    roomName: "Premier Ocean Pool Villa",
    roomCode: "V-07",
    checkIn: "2026-09-26",
    checkOut: "2026-10-02",
    nights: 6,
    totalAmount: "₹2,10,000",
    status: "Pending",
    loyaltyTier: "VIP",
    guestsCount: 2,
    specialRequests: "Helicopter helipad arrival transfer, Sunset yacht reservation on Day 2",
  },
  {
    id: "BK-8094",
    guestName: "Sir Julian Vance",
    guestEmail: "j.vance@mayfairholdings.co.uk",
    guestPhone: "+44 7700 900142",
    roomName: "Presidential Royal Suite",
    roomCode: "S-301",
    checkIn: "2026-09-24",
    checkOut: "2026-09-30",
    nights: 6,
    totalAmount: "₹3,40,000",
    status: "Checked In",
    loyaltyTier: "Platinum",
    guestsCount: 4,
    specialRequests: "Private cellar tasting with Sommelier, 24/7 dedicated butler",
  },
  {
    id: "BK-8095",
    guestName: "Dr. Elena Rostova",
    guestEmail: "elena.rostova@genevabiotech.ch",
    guestPhone: "+41 22 555 0184",
    roomName: "Cliffside Sanctuary Villa",
    roomCode: "C-102",
    checkIn: "2026-09-27",
    checkOut: "2026-10-01",
    nights: 4,
    totalAmount: "₹1,60,000",
    status: "Confirmed",
    loyaltyTier: "Gold",
    guestsCount: 1,
    specialRequests: "Quiet zone guarantee, Ayurvedic herbal bath preparation",
  },
  {
    id: "BK-8096",
    guestName: "Vikramaditya Singhania",
    guestEmail: "vikram@singhaniagroup.com",
    guestPhone: "+91 98210 77332",
    roomName: "Ocean Pool Villa",
    roomCode: "V-04",
    checkIn: "2026-09-22",
    checkOut: "2026-09-26",
    nights: 4,
    totalAmount: "₹1,40,000",
    status: "Checked Out",
    loyaltyTier: "Platinum",
    guestsCount: 2,
    specialRequests: "Late checkout at 3:00 PM accommodated",
  },
];

export const initialRooms: Room[] = [
  {
    id: "RM-1",
    code: "V-07",
    name: "Premier Ocean Pool Villa",
    type: "Villa",
    view: "Direct Ocean Front",
    wing: "North Coral Bay",
    ratePerNight: "₹35,000",
    status: "Ready",
    capacity: 3,
    sqm: 165,
    features: ["Private Infinity Pool", "Butler Pantry", "Outdoor Rain Shower", "Wine Reserve"],
    assignedStaff: "Deepak Sharma",
  },
  {
    id: "RM-2",
    code: "S-301",
    name: "Presidential Royal Suite",
    type: "Penthouse Suite",
    view: "360° Panoramic Coastline",
    wing: "The Grand Pavilion",
    ratePerNight: "₹65,000",
    status: "Occupied",
    capacity: 4,
    sqm: 240,
    features: ["Grand Piano", "Private Jacuzzi Terrace", "Dedicated Butler", "Private Dining Room"],
    currentGuest: "Sir Julian Vance",
    assignedStaff: "Maria Fernandes",
  },
  {
    id: "RM-3",
    code: "G-12",
    name: "Private Garden Villa",
    type: "Villa",
    view: "Tropical Botanical Gardens",
    wing: "Orchid Sanctuary",
    ratePerNight: "₹28,000",
    status: "Occupied",
    capacity: 3,
    sqm: 120,
    features: ["Sunken Garden Bath", "Private Hammock Grove", "Espresso Bar", "Bespoke Scents"],
    currentGuest: "Rahul Mehta",
    assignedStaff: "Karan Joshi",
  },
  {
    id: "RM-4",
    code: "R-204",
    name: "Deluxe Sea View Suite",
    type: "Suite",
    view: "Sunset Arabian Sea",
    wing: "Azure Terraces",
    ratePerNight: "₹24,000",
    status: "Occupied",
    capacity: 2,
    sqm: 95,
    features: ["Teak Balcony Daybed", "Marble En-suite", "Bose Sound System", "Pillow Menu"],
    currentGuest: "Priya Sharma",
    assignedStaff: "Sunita Rao",
  },
  {
    id: "RM-5",
    code: "C-102",
    name: "Cliffside Sanctuary Villa",
    type: "Villa",
    view: "Elevated Cliff Edge",
    wing: "Falcon Crest",
    ratePerNight: "₹40,000",
    status: "Ready",
    capacity: 2,
    sqm: 145,
    features: ["Glass-Bottom Plunge Pool", "Fire Pit Terrace", "Telescope Deck", "Organic Bar"],
    assignedStaff: "Amitava Sen",
  },
  {
    id: "RM-6",
    code: "R-205",
    name: "Deluxe Sea View Suite",
    type: "Suite",
    view: "Sunset Arabian Sea",
    wing: "Azure Terraces",
    ratePerNight: "₹24,000",
    status: "Housekeeping",
    capacity: 2,
    sqm: 95,
    features: ["Teak Balcony Daybed", "Marble En-suite", "Bose Sound System", "Pillow Menu"],
    assignedStaff: "Sunita Rao",
  },
  {
    id: "RM-7",
    code: "V-02",
    name: "Beachfront Lagoon Villa",
    type: "Villa",
    view: "Private Sand Beach",
    wing: "South Cove",
    ratePerNight: "₹38,000",
    status: "Maintenance",
    capacity: 4,
    sqm: 175,
    features: ["Private Boardwalk to Beach", "Plunge Pool", "Outdoor Teppanyaki", "Kayak Bay"],
    assignedStaff: "Ramesh Pillai",
  },
  {
    id: "RM-8",
    code: "G-14",
    name: "Royal Botanical Villa",
    type: "Villa",
    view: "Private Lotus Pond",
    wing: "Orchid Sanctuary",
    ratePerNight: "₹32,000",
    status: "Ready",
    capacity: 3,
    sqm: 130,
    features: ["Lotus Pavilion", "Outdoor Stone Tub", "Aromatherapy Shower", "Butler Service"],
    assignedStaff: "Karan Joshi",
  },
];

export const initialGuests: Guest[] = [
  {
    id: "GST-1",
    name: "Sir Julian Vance",
    email: "j.vance@mayfairholdings.co.uk",
    country: "United Kingdom",
    avatar: "JV",
    loyaltyTier: "Platinum",
    loyaltyPoints: 3450,
    totalStays: 7,
    totalSpent: "₹14,80,000",
    currentRoom: "S-301 · Presidential Suite",
    preferences: "Prefers Chateau Margaux 2015, Morning English Breakfast in bed at 08:00, Daily The Times printout",
    documentId: "GB-PASSPORT-902184",
    status: "In Residence",
  },
  {
    id: "GST-2",
    name: "Priya Sharma",
    email: "priya.sharma@luxmail.com",
    country: "India",
    avatar: "PS",
    loyaltyTier: "Platinum",
    loyaltyPoints: 2180,
    totalStays: 4,
    totalSpent: "₹4,20,000",
    currentRoom: "R-204 · Deluxe Sea View",
    preferences: "Allergen: Shellfish. Enjoys sunset yoga and cold-pressed Valencia orange juice",
    documentId: "IN-AADHAAR-883190",
    status: "In Residence",
  },
  {
    id: "GST-3",
    name: "Lady Ananya Iyer",
    email: "ananya.iyer@heritage.org",
    country: "India",
    avatar: "AI",
    loyaltyTier: "VIP",
    loyaltyPoints: 5820,
    totalStays: 9,
    totalSpent: "₹19,50,000",
    currentRoom: "V-07 · Pool Villa (Assigned)",
    preferences: "Always reserves private yacht for full sunset cruise; prefers silk pillowcases and organic spa oils",
    documentId: "IN-PASSPORT-440192",
    status: "Arriving Today",
  },
  {
    id: "GST-4",
    name: "Rahul Mehta",
    email: "rahul.mehta@investcorp.in",
    country: "India",
    avatar: "RM",
    loyaltyTier: "Gold",
    loyaltyPoints: 1420,
    totalStays: 3,
    totalSpent: "₹3,10,000",
    currentRoom: "G-12 · Garden Villa",
    preferences: "High-speed Ethernet required for international teleconferences; strictly vegetarian",
    documentId: "IN-PAN-ABCDE1234F",
    status: "In Residence",
  },
  {
    id: "GST-5",
    name: "Dr. Elena Rostova",
    email: "elena.rostova@genevabiotech.ch",
    country: "Switzerland",
    avatar: "ER",
    loyaltyTier: "Gold",
    loyaltyPoints: 1250,
    totalStays: 2,
    totalSpent: "₹2,80,000",
    currentRoom: "C-102 · Cliffside Villa",
    preferences: "Deep-tissue massage at Ocean Spa daily at 17:00; Sparkling San Pellegrino in suite",
    documentId: "CH-PASSPORT-772901",
    status: "In Residence",
  },
];

export const initialOrders: RestaurantOrder[] = [
  {
    id: "KOT-301",
    table: "Table 4 · Sunset Terrace",
    venue: "Sunset Terrace (Fine Dining)",
    guestName: "Sir Julian Vance",
    items: [
      "Grilled Chilean Sea Bass with Saffron Foam",
      "Black Truffle & Wild Morel Risotto",
      "Meursault Premier Cru 2020 (Bottle)",
    ],
    totalAmount: "₹14,500",
    time: "19:15",
    stage: "Preparing",
  },
  {
    id: "KOT-302",
    table: "Table 9 · The Ocean Club",
    venue: "The Ocean Club (Seafood & Grill)",
    guestName: "Priya Sharma",
    items: [
      "Pan-seared Coral Bay Scallops (substituted for King Oyster Mushroom)",
      "Avocado & Palm Heart Carpaccio",
      "Dom Pérignon Vintage 2013",
    ],
    totalAmount: "₹22,000",
    time: "19:28",
    stage: "Plated",
  },
  {
    id: "KOT-303",
    table: "Cabana 2 · Azure Pool Lounge",
    venue: "Azure Lounge (Cocktails & Tapas)",
    guestName: "Rahul Mehta",
    items: [
      "Wood-fired Artisanal Fig & Goat Cheese Flatbread",
      "Heirloom Tomato Gazpacho",
      "Virgin Yuzu Sparkler x2",
    ],
    totalAmount: "₹4,200",
    time: "19:40",
    stage: "Received",
  },
  {
    id: "KOT-300",
    table: "Private Dining Cellar",
    venue: "The Sommelier Cellar",
    guestName: "Vikramaditya Singhania",
    items: [
      "7-Course Degustation with Grand Cru Pairing",
      "A5 Miyazaki Wagyu Tenderloin",
      "Valrhona Dark Chocolate Soufflé",
    ],
    totalAmount: "₹48,000",
    time: "18:30",
    stage: "Served",
  },
];

export const initialHousekeeping: HousekeepingTask[] = [
  {
    id: "HK-101",
    roomCode: "V-07",
    roomName: "Premier Ocean Pool Villa",
    priority: "VIP Arrival",
    taskType: "VIP Arrival Inspection & Orchid Welcome Arrangement",
    assignedTo: "Deepak Sharma",
    dueTime: "12:00 PM",
    status: "Completed",
  },
  {
    id: "HK-102",
    roomCode: "S-301",
    roomName: "Presidential Royal Suite",
    priority: "High",
    taskType: "Daily Midday Refresh & Fresh Linen Change",
    assignedTo: "Maria Fernandes",
    dueTime: "01:30 PM",
    status: "Inspected",
  },
  {
    id: "HK-103",
    roomCode: "R-205",
    roomName: "Deluxe Sea View Suite",
    priority: "Standard",
    taskType: "Post-checkout Deep Sanitize & Teak Balcony Polish",
    assignedTo: "Sunita Rao",
    dueTime: "02:30 PM",
    status: "In Progress",
  },
  {
    id: "HK-104",
    roomCode: "G-12",
    roomName: "Private Garden Villa",
    priority: "Turn-down",
    taskType: "Evening Turn-down Service, Lavender Mist & Pillow Menu",
    assignedTo: "Karan Joshi",
    dueTime: "07:00 PM",
    status: "Pending",
  },
];

export const initialNotifications: ResortNotification[] = [
  {
    id: "NOTIF-1",
    title: "VIP Arrival: Lady Ananya Iyer",
    detail: "Helicopter arrival scheduled at 14:15. Helipad buggy and champagne welcome ready at Pavilion A.",
    time: "10 mins ago",
    department: "Concierge",
    unread: true,
    priority: "urgent",
  },
  {
    id: "NOTIF-2",
    title: "Suite S-301 Inspection Approved",
    detail: "Presidential Suite 301 passed 5-star QA inspection checklist with 100% rating.",
    time: "25 mins ago",
    department: "Housekeeping",
    unread: true,
  },
  {
    id: "NOTIF-3",
    title: "Sunset Terrace Dinner Fully Booked",
    detail: "Sunset Terrace fine dining has reached 100% reservation capacity for 20:00 seating.",
    time: "1 hour ago",
    department: "Kitchen",
    unread: false,
  },
  {
    id: "NOTIF-4",
    title: "High Tide Advisory",
    detail: "High tide expected at 17:45 (+2.1m). Coastal security has secured the south beach loungers.",
    time: "2 hours ago",
    department: "General",
    unread: false,
  },
];

// -------------------------------------------------------------
// RRMS Extended Datasets: Accounts, Services, Folios, Support, Reviews, Lost & Found, Admin
// -------------------------------------------------------------

export const initialAccounts: Account[] = [
  {
    id: "ACC-GM",
    name: "Amol Muruskar",
    email: "amol.gm@palmgrove.com",
    role: "General Manager",
    module: "Management",
    avatar: "AM",
    shift: "Executive (Full Access)",
  },
  {
    id: "ACC-REC",
    name: "Maya Patel",
    email: "maya.patel@palmgrove.com",
    role: "Receptionist",
    module: "Staff",
    avatar: "MP",
    shift: "Morning (07:00 — 15:30)",
  },
  {
    id: "ACC-HK",
    name: "Sunita Rao",
    email: "sunita.rao@palmgrove.com",
    role: "Housekeeper",
    module: "Staff",
    avatar: "SR",
    shift: "Day Shift (08:00 — 16:30)",
  },
  {
    id: "ACC-CASH",
    name: "Rohan Mehta",
    email: "rohan.mehta@palmgrove.com",
    role: "Cashier",
    module: "Staff",
    avatar: "RM",
    shift: "Audit & Folios (10:00 — 18:30)",
  },
  {
    id: "ACC-CHEF",
    name: "Chef Marco Rossi",
    email: "marco.chef@palmgrove.com",
    role: "Chef F&B",
    module: "Staff",
    avatar: "MR",
    shift: "Evening Service (14:00 — 23:00)",
  },
  {
    id: "ACC-MAINT",
    name: "Karan Joshi",
    email: "karan.joshi@palmgrove.com",
    role: "Maintenance",
    module: "Staff",
    avatar: "KJ",
    shift: "Engineering (08:00 — 17:00)",
  },
  {
    id: "ACC-GST",
    name: "Dr. Elena Rostova",
    email: "elena.rostova@genevabiotech.ch",
    role: "Guest",
    module: "Guest",
    avatar: "ER",
    assignedGuestId: "GST-5",
    assignedRoomCode: "C-102",
  },
];

export const initialServices: ResortServiceItem[] = [
  {
    id: "SRV-1",
    name: "Ayurvedic Coastal Herbal Spa Ritual",
    category: "Spa",
    price: 6500,
    duration: "90 mins",
    description: "Deep tissue organic warm herbal oil massage with sound bowl healing and sea salt foot scrub.",
    availability: "08:00 — 21:00",
  },
  {
    id: "SRV-2",
    name: "Private Candlelight Beachfront Dinner",
    category: "Dining",
    price: 12000,
    duration: "2.5 hours",
    description: "Exclusive 5-course seafood degustation menu prepared by a dedicated chef beside gentle coastal tides.",
    availability: "19:00 & 21:00",
  },
  {
    id: "SRV-3",
    name: "Rolls-Royce Ghost Airport Chauffeur",
    category: "Transport",
    price: 4500,
    duration: "Per Trip",
    description: "Private luxury airport arrival or departure in our bespoke climate-controlled Rolls-Royce Ghost.",
    availability: "24/7 On Demand",
  },
  {
    id: "SRV-4",
    name: "Sunset Yacht Cruise & Dom Pérignon",
    category: "Experience",
    price: 18500,
    duration: "3 hours",
    description: "Private twin-deck catamaran charter with sommelier caviar tasting along the secluded marine cliffs.",
    availability: "16:30 — 19:30",
  },
  {
    id: "SRV-5",
    name: "Royal Beluga Caviar & Champagne In-Suite",
    category: "Dining",
    price: 8000,
    duration: "Instant",
    description: "50g Royal Ossetra Caviar, traditional blinis, crème fraîche, and a chilled bottle of Laurent-Perrier.",
    availability: "24 Hours",
  },
  {
    id: "SRV-6",
    name: "Express Eco-Silk Laundry & Steam Press",
    category: "Laundry",
    price: 1800,
    duration: "4 hours",
    description: "Hand garment steaming, lavender wardrobe packaging, and delicate garment care delivered in woven baskets.",
    availability: "07:00 — 20:00",
  },
];

export const initialServiceBookings: ServiceBooking[] = [
  {
    id: "SBK-501",
    reservationId: "BK-8091",
    guestName: "Priya Sharma",
    roomCode: "R-204",
    serviceId: "SRV-1",
    serviceName: "Ayurvedic Coastal Herbal Spa Ritual",
    category: "Spa",
    amount: 6500,
    scheduledDate: "2026-09-28",
    scheduledTime: "17:00",
    status: "Accepted",
    notes: "Couple's suite requested. Jasmine and lemongrass aroma.",
  },
  {
    id: "SBK-502",
    reservationId: "BK-8094",
    guestName: "Sir Julian Vance",
    roomCode: "S-301",
    serviceId: "SRV-4",
    serviceName: "Sunset Yacht Cruise & Dom Pérignon",
    category: "Experience",
    amount: 18500,
    scheduledDate: "2026-09-29",
    scheduledTime: "16:30",
    status: "In progress",
    notes: "Catamaran prepared with sommelier cellar selections.",
  },
  {
    id: "SBK-503",
    reservationId: "BK-8095",
    guestName: "Dr. Elena Rostova",
    roomCode: "C-102",
    serviceId: "SRV-1",
    serviceName: "Ayurvedic Coastal Herbal Spa Ritual",
    category: "Spa",
    amount: 6500,
    scheduledDate: "2026-09-28",
    scheduledTime: "16:00",
    status: "Requested",
    notes: "Prefers female therapist. Emphasis on shoulder & neck therapy.",
  },
  {
    id: "SBK-504",
    reservationId: "BK-8092",
    guestName: "Rahul Mehta",
    roomCode: "G-12",
    serviceId: "SRV-6",
    serviceName: "Express Eco-Silk Laundry & Steam Press",
    category: "Laundry",
    amount: 1800,
    scheduledDate: "2026-09-27",
    scheduledTime: "11:00",
    status: "Completed",
    notes: "3 formal linen shirts steamed and delivered.",
  },
];

export const initialFolios: ReservationFolio[] = [
  {
    reservationId: "BK-8091",
    guestName: "Priya Sharma",
    roomCode: "R-204",
    taxRatePercent: 18,
    discountAmount: 4800,
    charges: [
      { id: "CHG-101", date: "2026-09-25", description: "Deluxe Sea View Suite (Night 1)", category: "Room", amount: 24000 },
      { id: "CHG-102", date: "2026-09-26", description: "Deluxe Sea View Suite (Night 2)", category: "Room", amount: 24000 },
      { id: "CHG-103", date: "2026-09-27", description: "Deluxe Sea View Suite (Night 3)", category: "Room", amount: 24000 },
      { id: "CHG-104", date: "2026-09-28", description: "Deluxe Sea View Suite (Night 4)", category: "Room", amount: 24000 },
      { id: "CHG-105", date: "2026-09-26", description: "Sunset Terrace Dinner Folio Transfer", category: "Dining", amount: 22000 },
      { id: "CHG-106", date: "2026-09-27", description: "Ayurvedic Couple Spa Ritual", category: "Service", amount: 6500 },
    ],
    payments: [
      { id: "PAY-1", date: "2026-09-25", amount: 50000, method: "Credit Card", type: "Payment", reference: "VISA-****4019" },
      { id: "PAY-2", date: "2026-09-27", amount: 20000, method: "UPI", type: "Payment", reference: "UPI/20260927/9012" },
    ],
  },
  {
    reservationId: "BK-8095",
    guestName: "Dr. Elena Rostova",
    roomCode: "C-102",
    taxRatePercent: 18,
    discountAmount: 8000,
    charges: [
      { id: "CHG-201", date: "2026-09-27", description: "Cliffside Sanctuary Villa (Night 1)", category: "Room", amount: 40000 },
      { id: "CHG-202", date: "2026-09-28", description: "Cliffside Sanctuary Villa (Night 2)", category: "Room", amount: 40000 },
      { id: "CHG-203", date: "2026-09-28", description: "Ayurvedic Deep Tissue Treatment", category: "Service", amount: 6500 },
      { id: "CHG-204", date: "2026-09-27", description: "Room Service San Pellegrino & Fruit Platter", category: "Dining", amount: 1850 },
    ],
    payments: [
      { id: "PAY-201", date: "2026-09-27", amount: 40000, method: "Credit Card", type: "Payment", reference: "MC-****8812" },
    ],
  },
  {
    reservationId: "BK-8094",
    guestName: "Sir Julian Vance",
    roomCode: "S-301",
    taxRatePercent: 18,
    discountAmount: 15000,
    charges: [
      { id: "CHG-301", date: "2026-09-24", description: "Presidential Royal Suite (Night 1-6)", category: "Room", amount: 340000 },
      { id: "CHG-302", date: "2026-09-26", description: "Private Yacht Catamaran Cruise", category: "Service", amount: 18500 },
      { id: "CHG-303", date: "2026-09-25", description: "Sommelier Rare Vintage Tasting", category: "Dining", amount: 14500 },
    ],
    payments: [
      { id: "PAY-301", date: "2026-09-24", amount: 200000, method: "Wire Transfer", type: "Payment", reference: "SWIFT-HSBC-0091" },
    ],
  },
];

export const initialSupportTickets: SupportTicket[] = [
  {
    id: "TCK-101",
    guestId: "GST-5",
    guestName: "Dr. Elena Rostova",
    roomCode: "C-102",
    subject: "Spa appointment timing adjustment",
    description: "Could I please reschedule my afternoon Ayurvedic treatment from 16:00 to 17:30 due to a virtual meeting?",
    category: "Spa",
    priority: "High",
    status: "In progress",
    createdAt: "Today, 11:20 AM",
    assignedStaff: "Leila Nair (Spa Director)",
    response: "Certainly Dr. Rostova. The Ocean Pavilion therapist has reserved 17:30 exclusively for you.",
  },
  {
    id: "TCK-102",
    guestId: "GST-2",
    guestName: "Priya Sharma",
    roomCode: "R-204",
    subject: "Extra hypoallergenic pillows request",
    description: "Please deliver 2 extra goose-down hypoallergenic pillows to Suite 204 before evening turn-down.",
    category: "Housekeeping",
    priority: "Standard",
    status: "Resolved",
    createdAt: "Today, 09:45 AM",
    assignedStaff: "Sunita Rao",
    response: "Delivered to suite at 10:15 AM.",
  },
  {
    id: "TCK-103",
    guestId: "GST-4",
    guestName: "Rahul Mehta",
    roomCode: "G-12",
    subject: "Terrace reading lamp flickering",
    description: "The bronze reading lamp on the garden terrace desk is flickering intermittently.",
    category: "Maintenance",
    priority: "Standard",
    status: "Open",
    createdAt: "Today, 12:10 PM",
    assignedStaff: "Karan Joshi",
  },
  {
    id: "TCK-104",
    guestId: "GST-1",
    guestName: "Sir Julian Vance",
    roomCode: "S-301",
    subject: "Private Sommelier Cellar Visit",
    description: "Requesting a 45-minute private cellar tour with Head Sommelier Jean-Luc before dinner.",
    category: "Food & Beverage",
    priority: "High",
    status: "Resolved",
    createdAt: "Yesterday, 04:30 PM",
    assignedStaff: "Chef Marco Rossi",
    response: "Sommelier Jean-Luc greeted Sir Julian at 18:30 in the Reserva Cellar.",
  },
];

export const initialReviews: GuestReview[] = [
  {
    id: "REV-1",
    reservationId: "BK-8096",
    guestId: "GST-6",
    guestName: "Vikramaditya Singhania",
    roomName: "Ocean Pool Villa (V-04)",
    overallRating: 5,
    roomRating: 5,
    serviceRating: 5,
    title: "Unmatched Indian Ocean Luxury & Discretion",
    comment: "From the private helicopter transfer to the exquisite private dining on the sands, Palm Grove exceeds even top Mediterranean resort standards. The private plunge pool overlooking the reef was sheer perfection.",
    date: "2026-09-26",
    verifiedStay: true,
  },
  {
    id: "REV-2",
    reservationId: "BK-8095",
    guestId: "GST-5",
    guestName: "Dr. Elena Rostova",
    roomName: "Cliffside Sanctuary Villa (C-102)",
    overallRating: 5,
    roomRating: 5,
    serviceRating: 5,
    title: "Total Tranquility and World-Class Wellness",
    comment: "The architectural lines and the silence of the Cliffside Sanctuary are meditative. The Ayurvedic therapists are masterfully trained. A true restorative oasis.",
    date: "2026-09-28",
    verifiedStay: true,
  },
  {
    id: "REV-3",
    reservationId: "BK-8092",
    guestId: "GST-4",
    guestName: "Rahul Mehta",
    roomName: "Private Garden Villa (G-12)",
    overallRating: 4,
    roomRating: 4,
    serviceRating: 5,
    title: "Impeccable Service & Sublime Cuisine",
    comment: "The staff's attention to my dietary requirements was seamless. Fast fiber Wi-Fi throughout the lush tropical gardens allowed me to work uninterrupted. Will return with family.",
    date: "2026-09-27",
    verifiedStay: true,
  },
];

export const initialLostAndFound: LostAndFoundItem[] = [
  {
    id: "LF-301",
    itemName: "Montblanc Meisterstück Rose Gold Pen",
    category: "Accessories",
    foundLocation: "Library Lounge, Pavilion C",
    foundDate: "2026-09-27",
    foundBy: "Maya Patel",
    storageLocation: "Front Desk Vault A-14",
    status: "Stored in Vault",
    notes: "Engraved with initials 'J.V.'. Belongs to Sir Julian Vance.",
  },
  {
    id: "LF-302",
    itemName: "Apple iPad Pro 13-inch (Space Black)",
    category: "Electronics",
    foundLocation: "Sunset Terrace Table 6",
    foundDate: "2026-09-26",
    foundBy: "Ramesh Pillai",
    storageLocation: "Front Desk Vault B-02",
    status: "Returned to Guest",
    claimedByGuest: "Vikramaditya Singhania",
    contactNumber: "+91 98210 77332",
    notes: "Handed over and verified with device passcode.",
  },
  {
    id: "LF-303",
    itemName: "Ray-Ban Aviator Polarized Sunglasses",
    category: "Accessories",
    foundLocation: "Infinity Pool Cabana 4",
    foundDate: "2026-09-28",
    foundBy: "Sunita Rao",
    storageLocation: "Front Desk Vault A-08",
    status: "Stored in Vault",
    notes: "Tortoise gold frame, brown gradient lenses.",
  },
];

export const initialPolicies: ResortPolicy[] = [
  {
    id: "POL-1",
    key: "check_in_time",
    title: "Standard Check-in Time",
    value: "14:00 (2:00 PM)",
    category: "Check-in/Out",
    description: "Guaranteed suite readiness time. VIP arrivals enjoy early check-in subject to villa turnaround.",
  },
  {
    id: "POL-2",
    key: "check_out_time",
    title: "Standard Check-out Time",
    value: "11:00 (11:00 AM)",
    category: "Check-in/Out",
    description: "Late checkout up to 16:00 complimentary for Platinum & VIP Tier guests upon availability.",
  },
  {
    id: "POL-3",
    key: "tax_rate",
    title: "Luxury Hospitality GST / Service Charge",
    value: "18% GST + 5% Luxury Surcharge",
    category: "Financial",
    description: "Applicable on room tariffs, fine dining, charter services, and spa rituals.",
  },
  {
    id: "POL-4",
    key: "cancellation_window",
    title: "Complimentary Cancellation Window",
    value: "48 Hours Prior to Arrival",
    category: "Operational",
    description: "Full refund for cancellations made 48 hours prior to check-in date. Peak holidays require 7 days notice.",
  },
  {
    id: "POL-5",
    key: "quiet_hours",
    title: "Sanctuary Quiet Hours",
    value: "22:30 — 06:30",
    category: "Guest Experience",
    description: "To protect coastal tranquility, non-amplified ambient acoustics only across outdoor pavilions.",
  },
];

export const initialPromotions: PromotionCode[] = [
  {
    id: "PROMO-1",
    code: "GOLDEN2026",
    discountPercent: 15,
    description: "Exclusive 15% luxury seasonal escape discount on all Oceanfront Villas.",
    validUntil: "2026-12-31",
    status: "Active",
    usageCount: 42,
    maxUsage: 100,
  },
  {
    id: "PROMO-2",
    code: "COASTALVIP",
    discountPercent: 20,
    description: "Private 20% concierge privilege code for returning Platinum and VIP members.",
    validUntil: "2026-11-30",
    status: "Active",
    usageCount: 18,
    maxUsage: 50,
  },
  {
    id: "PROMO-3",
    code: "SPAWELLNESS",
    discountPercent: 10,
    description: "10% privilege discount on all multi-day wellness and Ayurvedic healing packages.",
    validUntil: "2026-10-31",
    status: "Active",
    usageCount: 65,
    maxUsage: 200,
  },
];

export const rolePermissions: RolePermission[] = [
  {
    role: "General Manager",
    module: "Management",
    description: "Unrestricted operational, financial, human resource, and policy governance.",
    allowedTabs: ["dashboard", "bookings", "rooms", "people", "amenities", "billing", "operations", "administration"],
    canCheckInOut: true,
    canManageRates: true,
    canEditPolicies: true,
    canSettleFolio: true,
  },
  {
    role: "Receptionist",
    module: "Staff",
    description: "Front desk reservations, arrivals/departures, room assignments, guest folios.",
    allowedTabs: ["dashboard", "bookings", "rooms", "people", "amenities", "billing"],
    canCheckInOut: true,
    canManageRates: false,
    canEditPolicies: false,
    canSettleFolio: true,
  },
  {
    role: "Housekeeper",
    module: "Staff",
    description: "Room cleaning status, inspection checklists, turn-down duties, Lost & Found.",
    allowedTabs: ["dashboard", "rooms", "operations"],
    canCheckInOut: false,
    canManageRates: false,
    canEditPolicies: false,
    canSettleFolio: false,
  },
  {
    role: "Cashier",
    module: "Staff",
    description: "Folio audits, guest billing, payment receipting, refunds, financial ledger.",
    allowedTabs: ["dashboard", "bookings", "billing", "people"],
    canCheckInOut: false,
    canManageRates: false,
    canEditPolicies: false,
    canSettleFolio: true,
  },
  {
    role: "Chef F&B",
    module: "Staff",
    description: "Restaurant and in-suite dining order dispatch, culinary services.",
    allowedTabs: ["dashboard", "amenities", "operations"],
    canCheckInOut: false,
    canManageRates: false,
    canEditPolicies: false,
    canSettleFolio: false,
  },
  {
    role: "Maintenance",
    module: "Staff",
    description: "Facility maintenance, equipment repairs, room inspections, property care.",
    allowedTabs: ["dashboard", "rooms", "operations"],
    canCheckInOut: false,
    canManageRates: false,
    canEditPolicies: false,
    canSettleFolio: false,
  },
  {
    role: "Guest",
    module: "Guest",
    description: "Personalized guest portal: In-suite services, live folio, support tickets, reviews.",
    allowedTabs: ["dashboard", "amenities", "billing", "people"],
    canCheckInOut: false,
    canManageRates: false,
    canEditPolicies: false,
    canSettleFolio: true,
  },
];
